"""create_users_table

Revision ID: 058411e7a86e
Revises: 
Create Date: 2026-06-03 18:21:52.186869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '058411e7a86e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_google_user', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('idx_announcement_type_date', 'announcements', ['type', sa.literal_column('published_at DESC')], unique=False)
    op.create_unique_constraint('uix_source_chunk', 'document_chunks', ['source_type', 'source_id', 'chunk_index'])
    op.create_index('idx_event_category', 'events', ['category'], unique=False)
    op.create_index('idx_event_date', 'events', ['event_date'], unique=False)
    op.create_index('idx_gallery_publish_date', 'galleries', [sa.literal_column('publish_date DESC')], unique=False)
    op.create_index('idx_gallery_image_gallery', 'gallery_images', ['gallery_id'], unique=False)
    op.create_index('idx_institution_category_active', 'institutions', ['category', 'is_active'], unique=False)
    op.create_index('idx_job_active_date', 'job_listings', ['is_active', sa.literal_column('published_at DESC')], unique=False)
    op.create_index('idx_news_category', 'news', ['category'], unique=False)
    op.create_index('idx_news_published_at', 'news', [sa.literal_column('published_at DESC')], unique=False)
    op.create_index('idx_pharmacy_duty_date', 'pharmacies', ['duty_date'], unique=False)
    op.create_index('idx_pharmacy_name', 'pharmacies', ['name'], unique=False)
    op.create_index('idx_place_category_active', 'places', ['category', 'is_active'], unique=False)
    op.create_index('idx_place_name', 'places', ['name'], unique=False)
    op.create_index('idx_service_active_category', 'service_providers', ['is_active', 'category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_service_active_category', table_name='service_providers')
    op.drop_index('idx_place_name', table_name='places')
    op.drop_index('idx_place_category_active', table_name='places')
    op.drop_index('idx_pharmacy_name', table_name='pharmacies')
    op.drop_index('idx_pharmacy_duty_date', table_name='pharmacies')
    op.drop_index('idx_news_published_at', table_name='news')
    op.drop_index('idx_news_category', table_name='news')
    op.drop_index('idx_job_active_date', table_name='job_listings')
    op.drop_index('idx_institution_category_active', table_name='institutions')
    op.drop_index('idx_gallery_image_gallery', table_name='gallery_images')
    op.drop_index('idx_gallery_publish_date', table_name='galleries')
    op.drop_index('idx_event_date', table_name='events')
    op.drop_index('idx_event_category', table_name='events')
    op.drop_constraint('uix_source_chunk', 'document_chunks', type_='unique')
    op.drop_index('idx_announcement_type_date', table_name='announcements')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
